language: node_js
node_js:
   - "12.0"
script:
  - npm config set '//npm.pkg.github.com/:_authToken' "${GITHUB_TOKEN}"
  - npm i
  - npm run build
install:
  - npm i -g firebase-tools
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
