language: node_js
node_js:
  - "12.0"
install:
  - npm i -g firebase-tools
script:
  - npm config set '//npm.pkg.github.com/:_authToken' "${GITHUB_TOKEN}"
  - npm i
  - npm run build
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
